FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1903 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1903 AS build

WORKDIR /src
COPY ["MisTweet.csproj", "MisTweet/"]
RUN dotnet restore "MisTweet/MisTweet.csproj"
COPY . ./MisTweet/
WORKDIR "/src/MisTweet"
RUN DIR
RUN dotnet build "MisTweet.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MisTweet.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MisTweet.dll"]